Update to Python 3; Adapt to changed ACM confirmation
ImmobilienScout24/aws-cf-verified-ssl-certificate pull request #15
Opened 2021-01-15 15:59 UTC by christiandietze

- ACM confirmation mail for the certificate change and code had to be adapted
- building the code locally with Python 2.7 did not work --> updated to 3.8
- replaced urllib with requests

2021-01-15 16:08 UTC, heroldus requested changes
Great work!

2021-01-15 16:08 UTC, heroldus commented on lambda/cfnresponse.py
> +                     'PhysicalResourceId': physicalResourceId or context.log_stream_name, 'StackId': event['StackId'],
```suggestion
                     'PhysicalResourceId': physicalResourceId or context.log_stream_name, 
                     'StackId': event['StackId'],
```
For better readability, I would suggest to have one attribute per line.

2021-01-15 16:08 UTC, heroldus commented on lambda/cfnresponse.py
> +                     'RequestId': event['RequestId'], 'LogicalResourceId': event['LogicalResourceId'],
```suggestion
                     'RequestId': event['RequestId'], 
                     'LogicalResourceId': event['LogicalResourceId'],
```

2021-01-18 07:05 UTC, christiandietze commented
Thank you @heroldus 😄

2021-01-18 08:01 UTC, heroldus approved these changes
👍

2021-01-19 07:26 UTC, clipka24 approved these changes
LGTM 👍

2021-01-19 07:34 UTC, merged